### Lab | Inferential statistics - T-test & P-value

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import seaborn as sns

1. One tailed t-test - In a packing plant, a machine packs cartons with jars. It is supposed that a new machine will pack faster on the average than the machine currently used. To test that hypothesis, the times it takes each machine to pack ten cartons are recorded. The results, in seconds, are shown in the tables in the file files_for_lab/machine.txt. Assume that there is sufficient evidence to conduct the t test, does the data provide sufficient evidence to show if one machine is better than the other?



In [2]:
df1 = pd.read_csv('machine_new.txt', sep='\t')
print(df1.shape)
df1

(10, 2)


New machine  Old machine
0         42.1         42.7
1         41.0         43.6
2         41.3         43.8
3         41.8         43.3
4         42.4         42.5
5         42.8         43.5
6         43.2         43.1
7         42.3         41.7
8         41.8         44.0
9         42.7         44.1

Our hypothesis is:

$$H0: \mu_{New machine} > \mu_{Old machine} $$

$$H1: \mu_{New machine} <= \mu_{Old machine} $$

So we use one sided test.

In [3]:
st.ttest_ind(df1['New machine'], df1['Old machine'], equal_var=False)

Ttest_indResult(statistic=-3.3972307061176026, pvalue=0.00324224946631798)

How can be observed, it was possible to conduct a t test with 10 observations, but the small sample size may limit the ability to detect a statistically significant difference between the means of the two groups.

Pvalue < alpha, 0.003 < 0.05, so we reject H0, and could be that new machine is not better than old machine.

2. Matched Pairs Test - In this challenge we will compare dependent samples of data describing our Pokemon (file files_for_lab/pokemon.csv). Our goal is to see whether there is a significant difference between each Pokemon's defense and attack scores. Our hypothesis is that the defense and attack scores are equal. Compare the two columns to see if there is a statistically significant difference between them and comment your result.

In [4]:
df2 = pd.read_csv('pokemon.csv')
print(df2.shape)
df2

(800, 13)


#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

Our hypothesis is:

$$H0: \mu_{Attack} = \mu_{Defense}; \mu_{Attack}-\mu_{Defense}=0$$
$$H1: \mu_{Attack} \neq \mu_{Defense}; \mu_{Attack}-\mu_{Defense}\neq 0 $$

So we use one sided test.

In [5]:
st.ttest_rel(df2['Defense'], df2['Attack'])

Ttest_relResult(statistic=-4.325566393330478, pvalue=1.7140303479358558e-05)

Pvalue < alpha, 0.000017 < 0.05, so we reject H0. So, defense and attack scores are different.

### Inferential statistics - ANOVA

#### Context

Suppose you are working as an analyst in a microprocessor chip manufacturing plant. You have been given the task of analyzing a plasma etching process with respect to changing Power (in Watts) of the plasma beam. Data was collected and provided to you to conduct statistical analysis and check if changing the power of the plasma beam has any effect on the etching rate by the machine.  You will conduct ANOVA and check if there is any difference in the mean etching rate for different levels of power. You can find the data anova_lab_data.xlsx file in the files_for_lab folder

* State the null hypothesis

* State the alternate hypothesis

* What is the significance level

* What are the degrees of freedom of model, error terms, and total DoF

3. Your task is to understand the problem and write down all the steps to set up ANOVA. After the next lesson, we will ask you to solve this problem using Python. Here are the steps that you would need to work on: - Null hypothesis - Alternate hypothesis - Level of significance - Test statistic - P-value - F table

4. In this section, use the Python to conduct ANOVA.
What conclusions can you draw from the experiment and why?


In [6]:
df3 = pd.read_excel('anova_lab_data.xlsx')
print(df3.shape)
df3

(15, 2)


Power  Etching Rate
0   160 W          5.43
1   180 W          6.24
2   200 W          8.79
3   160 W          5.71
4   180 W          6.71
5   200 W          9.20
6   160 W          6.22
7   180 W          5.98
8   200 W          7.90
9   160 W          6.01
10  180 W          5.66
11  200 W          8.15
12  160 W          5.59
13  180 W          6.60
14  200 W          7.55

In [7]:
df3 = df3.rename(columns={'Etching Rate':'Rate'})
df3['Power'] = df3['Power'].str.replace('160 W', '160_W').str.replace('180 W', '180_W').str.replace('200 W', '200_W')

3. The hypothesis is:
$$H0: \mu_{1}=\mu_{2}=\mu_{3}=⋯=\mu_{n}$$
$$H1: \mu_{i}\neq\mu_{j}$$

for any i,j

H0: The mean etching rate for different levels of power are the same.

H1: The mean etching rate for different levels of power are not the same.

To conduct the test we use a level of significance of 5%. 

It is necessary to group the data into three groups, since we have three types of power: 160 W, 180 W and 200 W

4. In this section, I use the Python to conduct ANOVA.

In [8]:
df3.groupby(['Power']).agg({"Rate":np.mean})

Rate
Power       
160_W  5.792
180_W  6.238
200_W  8.318

In [9]:
df3['Power_count'] = df3.groupby('Power').cumcount() 
df3_pivot = df3.pivot(index='Power_count', columns='Power', values='Rate')
df3_pivot.columns = ['Power_'+str(x) for x in df3_pivot.columns.values]
df3_pivot.head()

Power_160_W  Power_180_W  Power_200_W
Power_count                                       
0                   5.43         6.24         8.79
1                   5.71         6.71         9.20
2                   6.22         5.98         7.90
3                   6.01         5.66         8.15
4                   5.59         6.60         7.55

In [10]:
df3_pivot.mean()

Power_160_W    5.792
Power_180_W    6.238
Power_200_W    8.318
dtype: float64

In [11]:
st.f_oneway(df3_pivot.Power_160_W, df3_pivot.Power_180_W, df3_pivot.Power_200_W)

F_onewayResult(statistic=36.87895470100505, pvalue=7.506584272358903e-06)

The conclusions are:

As the p_value is < alpha, 0.000007 < 0.05  we reject H0. So, the mean etching rate for different levels of power are not the same